### ISSUE TITLE
Alle Teile basierend auf Wiki-Fassung überarbeitet; Github nicht hilfreich

### ISSUE THREAD

**Issue by rschlenk** [FreifunkFranken/Verein#14]
Ich finde Github in diesem Stadium des Dokuments zu umständlich, zumal viele andere große Änderungen (Regensburger Satzung) noch nicht auf der Mainline sind. Habe daher einfach die komplette Satzung in ihrem alten Stand unabhängig bearbeitet, jeder Paragraph in einem eigenen Branch, leider aber aufeinander aufbauend. Müsste ich noch ändern, falls das jemand einzeln haben will. Ansonsten können die Commits auch einzeln übernommen werden.

Der Pull Request ist die #13. 
Kommentierung am besten pro Commit.

Bin beim Treffen Anfang September nicht da, vielleicht fließen ja trotzdem einige meiner Vorschläge ins Gesamtdokument.

**Comment by wuschLOR** [comment]
Würde eher das Gegenteil sagen Github ist perfekt für das Vorhaben wir haben nur kein Prozedere  festgelegt.

Würde dementsprechend ein Prozedere vorschlagen:
* pro Pullrequest nur darf nur 1 Paragraph bearbeitet werden (steht ja schon)
* jeder Pullrequest wird nach einer Woche gemerged wenn es nur ja stimmen (mehr als eine) und kein ausdrückliches Veto gibt.

Somit würde der Master aktueller sein und man könnte besser daran arbeiten.

**Comment by mojoaxel** [comment]
Ich würde jetzt ungern eine komplette Tool-Diskussion führen.

GitHub bietet die Möglichkeit Texte einfach zu bearbeiten, Änderungen nachzuvollziehen und einzeln zu diskutieren. Diese Möglichkeiten hat man z.B. mit einem Pad oder einem Wiki nur begrenzt.

Gerne können Vorschläge aber auch per eMail z.B. an mich geschickt werden. Ich mach mir gern die Arbeit diese in GitHub einzupflegen.
